project:
  type: website
  output-dir: docs
  
# ~ additional metadata ~

website:
  title: "nedasfr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Projects.qmd

format:
  html:
    theme: 
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

